function outtxt = tikzHeatMap(x,y,Z,clrmap,scale,extraAxisOptionsStr)

%-------------------------------------------------------------------------%
% Created: 02/28/16
%   -by JGM
%-------------------------------------------------------------------------%

%%%%%%%%%%%%%%%
% TO DO: 
% (4) increase saturation of heatmap??


% make a node in the lower corner
outtxt = ['\node[anchor=south west] (nodeOne) at ('...
    num2str(x(1)),',',num2str(y(1)),') {};',sprintf('\n')];

% the axis properties
outtxt = [outtxt,'\begin{axis}[',sprintf('\n\t'),...
    'view={0}{90},',sprintf('\n\t'),...
	'at={(nodeOne)},',sprintf('\n\t'),...
	'anchor=south west,',sprintf('\n\t'),...
  	'inner sep=0pt,',sprintf('\n\t'),...
  	'scale only axis,',sprintf('\n\t'),...
    'width = ',num2str(x(end)-x(1)),'cm,',sprintf('\n\t'),...
  	'height = ',num2str(y(end)-y(1)),'cm,',sprintf('\n\t'),...
    'scale = ',num2str(scale),',',sprintf('\n\t'),...
    extraAxisOptionsStr];
    %'xlabel={',xlabelStr,'},',sprintf('\n\t'),...
    %'ylabel={',ylabelStr,'},',sprintf('\n\t')];

% set up the colormap
outtxt = [outtxt,'colormap={mymap}{[1pt]%',sprintf('\n\t\t')];
for i = 1:size(clrmap,1)
    outtxt = [outtxt,'rgb(',num2str(i-1),'pt)=(',...
        num2str(clrmap(i,1)),',',...
        num2str(clrmap(i,2)),',',...
        num2str(clrmap(i,3)),');',sprintf('\n\t\t')];
end
outtxt = [outtxt,'},',sprintf('\n\t')];

% colorbar
outtxt = [outtxt,'colorbar,',sprintf('\n\t'),...
    'colorbar style={%',sprintf('\n\t\t'),...
    'separate axis lines,',sprintf('\n\t\t'),...
    'every outer x axis line/.append style={white!15!black},',sprintf('\n\t\t'),...
    'every x tick label/.append style={font=\color{white!15!black}},',sprintf('\n\t\t'),...
    'every outer y axis line/.append style={white!15!black},',sprintf('\n\t\t'),...
    'every y tick label/.append style={font=\color{white!15!black}}',sprintf('\n\t\t'),...
	'},',sprintf('\n\t'),...
    'point meta min=0.0001,',sprintf('\n\t'),...
    'point meta max=',num2str(max(Z(:))*1.00001),sprintf('\n\t\t')];

% close the axis bracket
outtxt = [outtxt,']',sprintf('\n')];


% the 3D plot (you will view it from above)
outtxt = [outtxt,'\addplot3[surf,shader=flat]',sprintf('\n'),...
    'coordinates{',sprintf('\n')];

% the coordinates themselves
for i = 1:length(x)
    for j = 1:length(y)
        outtxt = [outtxt,'(',num2str(x(i)),',',num2str(y(j)),...
            ',',num2str(Z(i,j)),')',sprintf('\n')];
    end
    outtxt = [outtxt,sprintf('\n')];
end
    
% close coordinates, axis
outtxt = [outtxt,'};',sprintf('\n'),'\end{axis}',sprintf('\n')];


end