function [extraCode,extraAxisOptions] = wrapperbits(yrtitle)
% wrapperbits   Strings that will be written at the beginning of tikz file

%-------------------------------------------------------------------------%
% Revised: 11/03/17
%   -changed to output just extraCode and extraAxisOptions, two cells of
%   strings
% Created: 03/29/17
%   by JGM
%-------------------------------------------------------------------------%


% extra pre-tikz code (top most)
ii = 1;
extraCode{ii} = '\providecommand{\thisTikzPicScale}{1}%';       ii=ii+1;
extraCode{ii} = '\providecommand{\thisXscale}{1}%';             ii=ii+1;
extraCode{ii} = '\providecommand{\thisYscale}{1}%';             ii=ii+1;
extraCode{ii} = '\providecommand{\thisXlabelopacity}{1}%';      ii=ii+1;
extraCode{ii} = '\providecommand{\thisYlabelopacity}{1}%';      ii=ii+1;
extraCode{ii} = '\providecommand{\thisXticklabelopacity}{1}%';  ii=ii+1;
extraCode{ii} = '\providecommand{\thisYticklabelopacity}{1}%';  ii=ii+1;
extraCode{ii} = '\provideboolean{SKIPLEGEND}%';                 ii=ii+1;
extraCode{ii} = '\provideboolean{SKIPTITLE}%';                  ii=ii+1;



% extra axis options
ii = 1;

% scale changers
extraAxisOptions{ii} = 'scale=\thisTikzPicScale';               ii=ii+1;
extraAxisOptions{ii} = 'x post scale=\thisXscale';              ii=ii+1;
extraAxisOptions{ii} = 'y post scale=\thisYscale';              ii=ii+1;

% label locators
extraAxisOptions{ii} = sprintf([...
    'every axis x label/.style={%%\n\t',...
    'at={(xticklabel cs:0.5)},%%\n\t',...
    'anchor=north,%%\n\t',...
    'opacity=\\thisXlabelopacity,%%\n',...
    '}']);                                                      ii=ii+1;
extraAxisOptions{ii} = sprintf([...
    'every axis y label/.style={%%\n',...
    '\tat={(ticklabel cs:0.5)},%%\n',...
    '\tanchor=south,%%\n',...
    '\trotate=90,%%\n',...
    '\topacity=\\thisYlabelopacity,%%\n',...
    '}']);                                                      ii=ii+1;

% tick label hiders
extraAxisOptions{ii} = sprintf([...
    'every x tick label/.style={%%\n',...
    '\topacity=\\thisXticklabelopacity,%%\n',...
    '}']);                                                      ii=ii+1;
extraAxisOptions{ii} = sprintf([...
    'every y tick label/.style={%%\n',...
    '\topacity=\\thisYticklabelopacity,%%\n',...
    '}']);                                                      ii=ii+1;

% legend hider
extraAxisOptions{ii} = sprintf([...
    'every axis legend/.append code={%%\n\t',...
    '\\ifthenelse{\\boolean{SKIPLEGEND}}{%%\n\t\t'...
    '\\renewcommand\\addlegendentry[2][]{}%%\n\t',...
    '}{}%%\n}']);                                               ii=ii+1;

% title hider
extraAxisOptions{ii} = sprintf([...
    'title={%%\n\t',...
    '\\ifthenelse{\\boolean{SKIPTITLE}}{%%\n\t',...
    '}{%%\n\t\t%s%%\n\t}%%\n}',...
    ],yrtitle);                                                 ii=ii+1;

end